using DBAWebsite.APP;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace DBAWebsite
{
    public partial class EditInventoryForm : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

            if (Application["Name"] != null)
            {
                lblhead_servername.Text = Application["Name"].ToString();
                lbl_servername.Text = Application["Name"].ToString();
            }

            Inventory_Number_autovalue.Text = "Autogenerated";

            editInventoryForm_lables_DataBinding();
            backup_type_dropdownlist_DataBinding();
            Business_contact_dropdownlist_DataBinding();
            location_id_dropdownlist_DataBinding();
            application_info_dropdownlist_DataBinding();
            ITcontact_person_dropdownlist_DataBinding();
            ITcontact_team_dropdownlist_DataBinding();
            Location_dropdownlist_DataBinding();
            Inventory_dropdownlist_DataBinding();
            Environment_dropdownlist_DataBinding();
            sox_complaint_dropdownlist_DataBinding();
        }


        protected void editInventoryForm_lables_DataBinding()
        {
            DataTable editInventoryFormlable_Info = new DataTable();

            using (SqlConnection con = new SqlConnection(ConfigurationManager.ConnectionStrings["myConnectionString"].ConnectionString))
            {

                try
                {
                    SqlCommand sqlCmd = new SqlCommand("select * from [dbo].[InventoryForm] where servername = @servername", con);
                    sqlCmd.Parameters.AddWithValue("@servername", lblhead_servername.Text);
                    SqlDataAdapter adapter = new SqlDataAdapter(sqlCmd);

                    adapter.Fill(editInventoryFormlable_Info);

                    if (editInventoryFormlable_Info.Rows.Count > 0)
                    {
                        lbl_servername_old.Text = editInventoryFormlable_Info.Rows[0]["ServerName"].ToString();
                        lbl_Inventory.Text = editInventoryFormlable_Info.Rows[0]["InventoryType"].ToString();
                        lbl_helpdeskid.Text = editInventoryFormlable_Info.Rows[0]["HelpDeskID"].ToString();
                        lbl_projectid.Text = editInventoryFormlable_Info.Rows[0]["ProjectID"].ToString();
                        lbl_Location.Text = editInventoryFormlable_Info.Rows[0]["Location"].ToString();
                        lbl_location_id.Text = editInventoryFormlable_Info.Rows[0]["LocationID"].ToString();
                        lbl_environment.Text = editInventoryFormlable_Info.Rows[0]["Environment"].ToString();
                        lbl_application_info.Text = editInventoryFormlable_Info.Rows[0]["ApplicationInfo"].ToString();
                        lbl_ITcontact_team.Text = editInventoryFormlable_Info.Rows[0]["ITContactTeam"].ToString();
                        lbl_ITcontact_person.Text = editInventoryFormlable_Info.Rows[0]["ITContactPerson"].ToString();
                        lbl_Business_contact.Text = editInventoryFormlable_Info.Rows[0]["BusinessContact"].ToString();
                        lbl_sox_complaint.Text = editInventoryFormlable_Info.Rows[0]["SOXComplaint"].ToString();
                        lbl_backup_type.Text = editInventoryFormlable_Info.Rows[0]["BackupType"].ToString();                       
                    }

                }
                catch (Exception ex)
                {

                }

            }
        }

        protected void Inventory_dropdownlist_DataBinding()
        {
            DataTable inventoryType = new DataTable();

            SqlDataReader reader;
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["myConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand("usp_WebFormSelect", conn))
            {
                try
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@query", SqlDbType.VarChar).Value = "inventorytype";
                    conn.Open();
                    reader = cmd.ExecuteReader();
                    inventoryType.Load(reader);
                    Inventory_dropdownlist.DataSource = inventoryType;
                    Inventory_dropdownlist.DataTextField = "InventoryType";
                    Inventory_dropdownlist.DataValueField = "InventoryType";
                    Inventory_dropdownlist.DataBind();
                    Logging.LogInfo("Successful binding on: Inventory Dropdown", true);
                }
                catch (Exception ex)
                {
                    Logging.LogException(ex, "Error while executing the SP: usp_WebFormSelect");
                }
            }
        }

        protected void Location_dropdownlist_DataBinding()
        {
            DataTable location_info = new DataTable();
            SqlDataReader reader;
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["myConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand("usp_WebFormSelect", conn))
            {
                try
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@query", SqlDbType.VarChar).Value = "location";
                    conn.Open();
                    reader = cmd.ExecuteReader();
                    location_info.Load(reader);
                    Location_dropdownlist.DataSource = location_info;
                    Location_dropdownlist.DataTextField = "Site Name";
                    Location_dropdownlist.DataValueField = "Site Name";
                    Location_dropdownlist.DataBind();
                    Logging.LogInfo("Successful binding on: Inventory Dropdown", true);
                }
                catch (Exception ex)
                {
                    Logging.LogException(ex, "Error while executing the SP: usp_WebFormSelect");
                }
            }


        }

        protected void Environment_dropdownlist_DataBinding()
        {
            DataTable environmentType = new DataTable();
            SqlDataReader reader;
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["myConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand("usp_WebFormSelect", conn))
            {
                try
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@query", SqlDbType.VarChar).Value = "editenvironment";
                    conn.Open();
                    reader = cmd.ExecuteReader();
                    environmentType.Load(reader);
                    Environment_dropdownlist.DataSource = environmentType;
                    Environment_dropdownlist.DataTextField = "Environment";
                    Environment_dropdownlist.DataValueField = "Environment";
                    Environment_dropdownlist.DataBind();
                    Logging.LogInfo("Successful binding on: Inventory Dropdown", true);
                }
                catch (Exception ex)
                {
                    Logging.LogException(ex, "Error while executing the SP: usp_WebFormSelect");
                }
            }
        }

        protected void ITcontact_team_dropdownlist_DataBinding()
        {
            DataTable contact_team = new DataTable();
            SqlDataReader reader;
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["myConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand("usp_WebFormSelect", conn))
            {
                try
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@query", SqlDbType.VarChar).Value = "itcontactteam";
                    conn.Open();
                    reader = cmd.ExecuteReader();
                    contact_team.Load(reader);
                    ITcontact_team_dropdownlist.DataSource = contact_team;
                    ITcontact_team_dropdownlist.DataTextField = "IT Contact Team";
                    ITcontact_team_dropdownlist.DataValueField = "IT Contact Team";
                    ITcontact_team_dropdownlist.DataBind();
                    Logging.LogInfo("Successful binding on: Inventory Dropdown", true);
                }
                catch (Exception ex)
                {
                    Logging.LogException(ex, "Error while executing the SP: usp_WebFormSelect");
                }
            }
        }

        protected void ITcontact_person_dropdownlist_DataBinding()
        {
            DataTable contact_person = new DataTable();
            SqlDataReader reader;
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["myConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand("usp_WebFormSelect", conn))
            {
                try
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@query", SqlDbType.VarChar).Value = "itcontactperson";
                    conn.Open();
                    reader = cmd.ExecuteReader();
                    contact_person.Load(reader);
                    ITcontact_person_dropdownlist.DataSource = contact_person;
                    ITcontact_person_dropdownlist.DataTextField = "displayName";
                    ITcontact_person_dropdownlist.DataValueField = "displayName";
                    ITcontact_person_dropdownlist.DataBind();
                    Logging.LogInfo("Successful binding on: Inventory Dropdown", true);
                }
                catch (Exception ex)
                {
                    Logging.LogException(ex, "Error while executing the SP: usp_WebFormSelect");
                }
            }


        }

        protected void sox_complaint_dropdownlist_DataBinding()
        {
            DataTable inventory_soxComplaint_info = new DataTable();
            SqlDataReader reader;
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["myConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand("usp_WebFormSelect", conn))
            {
                try
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@query", SqlDbType.VarChar).Value = "soxcompliant";
                    conn.Open();
                    reader = cmd.ExecuteReader();
                    inventory_soxComplaint_info.Load(reader);
                    sox_complaint_dropdownlist.DataSource = inventory_soxComplaint_info;
                    sox_complaint_dropdownlist.DataTextField = "Inventory_SoxComplaint";
                    sox_complaint_dropdownlist.DataValueField = "Inventory_SoxComplaint";
                    sox_complaint_dropdownlist.DataBind();
                    Logging.LogInfo("Successful binding on: Inventory Dropdown", true);
                }
                catch (Exception ex)
                {
                    Logging.LogException(ex, "Error while executing the SP: usp_WebFormSelect");
                }
            }

        }


        protected void backup_type_dropdownlist_DataBinding()
        {
            DataTable backupType = new DataTable();
            SqlDataReader reader;
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["myConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand("usp_WebFormSelect", conn))
            {
                try
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@query", SqlDbType.VarChar).Value = "backuptype";
                    conn.Open();
                    reader = cmd.ExecuteReader();
                    backupType.Load(reader);
                    backup_type_dropdownlist.DataSource = backupType;
                    backup_type_dropdownlist.DataTextField = "BackupType";
                    backup_type_dropdownlist.DataValueField = "BackupType";
                    backup_type_dropdownlist.DataBind();
                    Logging.LogInfo("Successful binding on: Inventory Dropdown", true);
                }
                catch (Exception ex)
                {
                    Logging.LogException(ex, "Error while executing the SP: usp_WebFormSelect");
                }
            }

        }

        protected void Business_contact_dropdownlist_DataBinding()
        {
            DataTable businessContact = new DataTable();
            SqlDataReader reader;
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["myConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand("usp_WebFormSelect", conn))
            {
                try
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@query", SqlDbType.VarChar).Value = "buscontact";
                    conn.Open();
                    reader = cmd.ExecuteReader();
                    businessContact.Load(reader);
                    Business_contact_dropdownlist.DataSource = businessContact;
                    Business_contact_dropdownlist.DataTextField = "Business Contact";
                    Business_contact_dropdownlist.DataValueField = "Business Contact";
                    Business_contact_dropdownlist.DataBind();
                    Logging.LogInfo("Successful binding on: Inventory Dropdown", true);
                }
                catch (Exception ex)
                {
                    Logging.LogException(ex, "Error while executing the SP: usp_WebFormSelect");
                }
            }
        }

        protected void location_id_dropdownlist_DataBinding()
        {
            DataTable location_ID = new DataTable();
            SqlDataReader reader;
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["myConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand("usp_WebFormSelect", conn))
            {
                try
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@query", SqlDbType.VarChar).Value = "locationid";
                    conn.Open();
                    reader = cmd.ExecuteReader();
                    location_ID.Load(reader);
                    location_id_dropdownlist.DataSource = location_ID;
                    location_id_dropdownlist.DataTextField = "Location ID";
                    location_id_dropdownlist.DataValueField = "Location ID";
                    location_id_dropdownlist.DataBind();
                    Logging.LogInfo("Successful binding on: Inventory Dropdown", true);
                }
                catch (Exception ex)
                {
                    Logging.LogException(ex, "Error while executing the SP: usp_WebFormSelect");
                }
            }

        }

        protected void application_info_dropdownlist_DataBinding()
        {
            DataTable application_Info = new DataTable();
            SqlDataReader reader;
            using (SqlConnection conn = new SqlConnection(ConfigurationManager.ConnectionStrings["myConnectionString"].ConnectionString))
            using (SqlCommand cmd = new SqlCommand("usp_WebFormSelect", conn))
            {
                try
                {
                    cmd.CommandType = CommandType.StoredProcedure;
                    cmd.Parameters.Add("@query", SqlDbType.VarChar).Value = "appinfo";
                    conn.Open();
                    reader = cmd.ExecuteReader();
                    application_Info.Load(reader);
                    application_info_dropdownlist.DataSource = application_Info;
                    application_info_dropdownlist.DataTextField = "Application Info";
                    application_info_dropdownlist.DataValueField = "Application Info";
                    application_info_dropdownlist.DataBind();
                    Logging.LogInfo("Successful binding on: Inventory Dropdown", true);
                }
                catch (Exception ex)
                {
                    Logging.LogException(ex, "Error while executing the SP: usp_WebFormSelect");
                }
            }

        }

        protected void submit_Click(object sender, EventArgs e)
        {
            string serverName = lblhead_servername.Text;

            string inventory_type = Inventory_dropdownlist.SelectedItem.Text;
            string inventorytype_notes = Request.Form["inv_inventorytype_notes"];

            string helpdesk_id = txt_helpdeskid.Text;
            string helpdeskid_notes = Request.Form["inv_helpdeskid_notes"];

            string project_id = txt_projectid.Text;
            string projectid_notes = Request.Form["inv_projectid_notes"];

            string location = Location_dropdownlist.SelectedItem.Text;
            string location_notes = Request.Form["inv_location_notes"];

            string location_id = location_id_dropdownlist.SelectedItem.Text;
            string locationid_notes = Request.Form["inv_locationid_notes"];

            string environment = Environment_dropdownlist.SelectedItem.Text;
            string environment_notes = Request.Form["inv_environment_notes"];

            string application_info = application_info_dropdownlist.SelectedItem.Text;
            string applicationinfo_notes = Request.Form["inv_applicationinfo_notes"];

            string ITcontact_team = ITcontact_team_dropdownlist.SelectedItem.Text;
            string ITcontactteam_notes = Request.Form["inv_itcontactteam_notes"];

            string ITcontact_person = ITcontact_person_dropdownlist.SelectedItem.Text;
            string ITcontactperson_notes = Request.Form["inv_itcontactperson_notes"];

            string business_contact = Business_contact_dropdownlist.SelectedItem.Text;
            string businesscontact_notes = Request.Form["inv_businesscontact_notes"];

            string sox_complaint = sox_complaint_dropdownlist.SelectedItem.Text;
            string soxcomplaint_notes = Request.Form["inv_soxcomplaint_notes"];

            string backup_type = backup_type_dropdownlist.SelectedItem.Text;
            string backuptype_notes = Request.Form["inv_backuptype_notes"];

            string overallinventory_notes = Request.Form["inv_overall_notes"];

            string connString = ConfigurationManager.ConnectionStrings["myConnectionString"].ConnectionString;
            SqlConnection conn = null;
            try
            {
                conn = new SqlConnection(connString);
                conn.Open();

                using (SqlCommand cmd = new SqlCommand())
                {
                    cmd.Connection = conn;
                    cmd.CommandType = CommandType.Text;
                    cmd.CommandText = "UPDATE InventoryForm  SET [InventoryType]=@inventorytype,[InventoryType_Notes]=@inventorytypenotes,[HelpDeskID]=@helpdeskid,[HelpDeskID_Notes]=@helpdeskidnotes,[ProjectID]=@projectid,[ProjectID_Notes]=@projectidnotes,[Location]=@location,[Location_Notes]=@locationnotes,[LocationID]=@locationid,[LocationID_Notes]=@locationidnotes,[Environment]=@environment,[Environment_Notes]=@environmentnotes,[ApplicationInfo]=@applicationinfo,[ApplicationInfo_Notes]=@applicationinfonotes,[ITContactTeam]=@itcontactteam,[ITContactTeam_Notes]=@itcontactteamnotes,[ITContactPerson]=@itcontactperson,[ITContactPerson_Notes]=@itcontactpersonnotes,[BusinessContact]=@businesscontact,[BusinessContact_Notes]=@businesscontactnotes,[SOXComplaint]=@soxcomplaint,[SOXComplaint_Notes]=@soxcomplaintnotes,[BackupType]=@backuptype,[BackupType_Notes]=@backuptypenotes,[OverallInventorynotes]=@overallinventorynotes WHERE [ServerName] = @serevrname";

                    SqlParameter[] param = new SqlParameter[29];

                    param[3] = new SqlParameter("@serevrname", SqlDbType.NVarChar, 50);
                    param[4] = new SqlParameter("@inventorytype", SqlDbType.NVarChar, 50);
                    param[5] = new SqlParameter("@inventorytypenotes", SqlDbType.NVarChar, 100);
                    param[6] = new SqlParameter("@helpdeskid", SqlDbType.NVarChar, 50);
                    param[7] = new SqlParameter("@helpdeskidnotes", SqlDbType.NVarChar, 100);
                    param[8] = new SqlParameter("@projectid", SqlDbType.NVarChar, 50);
                    param[9] = new SqlParameter("@projectidnotes", SqlDbType.NVarChar, 100);
                    param[10] = new SqlParameter("@location", SqlDbType.NVarChar, 50);
                    param[11] = new SqlParameter("@locationnotes", SqlDbType.NVarChar, 100);
                    param[12] = new SqlParameter("@locationid", SqlDbType.NVarChar, 50);
                    param[13] = new SqlParameter("@locationidnotes", SqlDbType.NVarChar, 100);
                    param[14] = new SqlParameter("@environment", SqlDbType.NVarChar, 50);
                    param[15] = new SqlParameter("@environmentnotes", SqlDbType.NVarChar, 100);
                    param[16] = new SqlParameter("@applicationinfo", SqlDbType.NVarChar, 50);
                    param[17] = new SqlParameter("@applicationinfonotes", SqlDbType.NVarChar, 100);
                    param[18] = new SqlParameter("@itcontactteam", SqlDbType.NVarChar, 50);
                    param[19] = new SqlParameter("@itcontactteamnotes", SqlDbType.NVarChar, 100);
                    param[20] = new SqlParameter("@itcontactperson", SqlDbType.NVarChar, 50);
                    param[21] = new SqlParameter("@itcontactpersonnotes", SqlDbType.NVarChar, 100);
                    param[22] = new SqlParameter("@businesscontact", SqlDbType.NVarChar, 50);
                    param[23] = new SqlParameter("@businesscontactnotes", SqlDbType.NVarChar, 100);
                    param[24] = new SqlParameter("@soxcomplaint", SqlDbType.NVarChar, 50);
                    param[25] = new SqlParameter("@soxcomplaintnotes", SqlDbType.NVarChar, 100);
                    param[26] = new SqlParameter("@backuptype", SqlDbType.NVarChar, 50);
                    param[27] = new SqlParameter("@backuptypenotes", SqlDbType.NVarChar, 100);
                    param[28] = new SqlParameter("@overallinventorynotes", SqlDbType.NVarChar, 100);


                    param[3].Value = serverName;
                    param[4].Value = inventory_type;
                    param[5].Value = inventorytype_notes;
                    param[6].Value = helpdesk_id;
                    param[7].Value = helpdeskid_notes;
                    param[8].Value = project_id;
                    param[9].Value = projectid_notes;
                    param[10].Value = location;
                    param[11].Value = location_notes;
                    param[12].Value = location_id;
                    param[13].Value = locationid_notes;
                    param[14].Value = environment;
                    param[15].Value = environment_notes;
                    param[16].Value = application_info;
                    param[17].Value = applicationinfo_notes;
                    param[18].Value = ITcontact_team;
                    param[19].Value = ITcontactteam_notes;
                    param[20].Value = ITcontact_person;
                    param[21].Value = ITcontactperson_notes;
                    param[22].Value = business_contact;
                    param[23].Value = businesscontact_notes;
                    param[24].Value = sox_complaint;
                    param[25].Value = soxcomplaint_notes;
                    param[26].Value = backup_type;
                    param[27].Value = backuptype_notes;
                    param[28].Value = overallinventory_notes;


                    for (int i = 3; i < param.Length; i++)
                    {
                        cmd.Parameters.Add(param[i]);
                    }


                    int rowsAffected = cmd.ExecuteNonQuery();
                    string url = ResolveUrl("~/EditInventoryForm.aspx");
                    if (rowsAffected == 1)
                        Response.Write(String.Format("<script>alert('The records are updated in to database successfully!');window.location='{0}';</script>", url));
                    else
                        Response.Write(String.Format("<script>alert('OOps there was an error while updating in to database!');window.location='{0}';</script>", url));
                }
            }
            catch (Exception ex)
            {
                string url = ResolveUrl("~/EditInventoryForm.aspx");
                Response.Write(String.Format("<script>alert('OOps there was an error while updating in to database!');window.location='{0}';</script>", url));
            }
            finally
            {
                if (conn != null)
                {
                    conn.Close();
                }
            }
        }
    }
}